### ISSUE TITLE
Add hooks for memmon to run a command before and after restarting a process

### ISSUE THREAD

**Issue by hvelarde** [Supervisor/superlance#102]
We have the following typical use case: Plone site with multiple instances running behind a web accelerator like Varnish, using memmon and httpok.

From time to time, memmon will need to restart an instance because of high memory consumption; Varnish has configured backend health check probes that test if the instances are available or not, and this probes have to play very nicely with the instances because requests hitting the backend are typically slow; for instance:

```
probe healthcheck {
    .interval = 10s; .request = "HEAD / HTTP/1.1"; .timeout = 3s;
}
```

As restarting a Plone instance is a time consuming process (typically, around 30 seconds), Varnish will not notice the instance is down for some time and will continue sending requests; the instance then came in and will be flooded with a lot of pending requests from Varnish.

The Varnish backend then behaves erratically for some time until the instance stabilizes.

What I would like to have? a hook to run a command before the instance is restarted and after is marked as running.

Then I would be able to configure something like this:

* memmon detects high memory usage
* pre-hook is run: `varnishadm backend.set_health instance1 sick`
* instance1 is restarted
* supervisor waits and marks it as running
* post-hook is run: `varnishadm backend.set_health instance1 auto`

This could be useful in other use cases also.

**Comment by hvelarde** [comment]
@djay @erral @mauritsvanrees @smcmahon what do you think?

**Comment by erral** [comment]
I haven't had such a usecase, but hooks that allow pluggability are good in general. :+1:  on my side if that count's for something

**Comment by hvelarde** [comment]
According with https://github.com/Supervisor/supervisor/issues/31 this can be achieved "executing a script that registers a signal handler for TERM, spawns a subprocess, then waits forever, and calls the save command then kills the subprocess when it gets a TERM."
