### ISSUE TITLE
memmon throwing 401 unauthorized when username and password used in unix_http_server

### ISSUE THREAD

**Issue by ksrivatsa** [Supervisor/superlance#105]
When authentication is used in the unix_http_server section and the same are credentials are used everywhere necessary like supervisorctl, memmon throws 401 unauthorized when it tries to create the ServerProxy in the main method. The supervisorctl is working fine though and the inet_http_server is also setup. What could be the issue?

It seems to expect the SUPERVISOR_USERNAME, SUPERVISOR_PASSWORD and the SUPERVISOR_SERVER_URL to be present in the env. Should we set it explicitly?

**Comment by ksrivatsa** [comment]
This worked by specifying the env variables in the section of the program.

environment=SUPERVISOR_USERNAME="blah",SUPERVISOR_PASSWORD="plop",SUPERVISOR_SERVER_URL="unix:///path/to/supervisor.sock"

This will save some time if it is mentioned in the docs. https://superlance.readthedocs.io/en/latest/memmon.html

**Comment by mnaberez** [comment]
Closing since you seem to have resolved your issue.  The [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users) is the usual place to discuss Supervisor and eventlisteners.

**Comment by ksrivatsa** [comment]
Shouldn't it be mentioned in the docs?

**Comment by mnaberez** [comment]
That sounds fine if you'd like to submit a pull request for it.  Thanks.

**Comment by ksrivatsa** [comment]
#106 Please do check and merge it. :)

**Comment by ksrivatsa** [comment]
Any problem?

**Comment by bstock92** [comment]
Thanks for the suggested fix. It seems to also solve 401 Unauthorized (`xmlrpclib.ProtocolError: <ProtocolError for 127.0.0.1/RPC2: 401 Unauthorized>`) when using httpok with a unix_http_server and credentials. It's odd that this doesn't seem to be documented anywhere in supervisor's documentation, or I haven't found it.

**Comment by wdv4758h** [comment]
Thanks for the tips. This solves my problem.
