### ISSUE TITLE
httpok doesnt work if timeout is < 10

### ISSUE THREAD

**Issue by skaufman-socialflow** [Supervisor/superlance#110]
This sounds unlikely but seems to be the case:

This commit: https://github.com/Supervisor/superlance/commit/0e6fb2d04a5eb144a2190e61745b6c915ded57e8#diff-d3d6eafafd2e31ce38ebab9e08f156eaL180

changed the logic for the retry loop. retry_time is hardcoded to 10 in httpok, so if timeout is < 10,
`range(self.timeout // (self.retry_time or 1) - 1 ,  -1, -1):`
becomes
`range(5 // 10 - 1 ,  -1, -1):`
simplifies to
`range(-1 ,  -1, -1):` 
which will never execute because it is `[]`.

I attempted to write a test case but I'm not really skilled enough to dissect the http_ok test file.

**Comment by mnaberez** [comment]
@do3cc Can you please look at this?

**Comment by do3cc** [comment]
@skaufman-socialflow you are right. It seems I assumed that timeout will always be bigger than retry_time

**Comment by skaufman-socialflow** [comment]
@do3cc awesome thanks so much for the quick turnaround and bugfix! We use httpok a good amount across our supervisor processes and it has been a great help.

**Comment by Brijesh-quo** [comment]
@mnaberez It seems, the fix for this issue is not available on pip. One has to install it via Github to get this fix.
