### ISSUE TITLE
Superlance to send alerts to Slack channel

### ISSUE THREAD

**Issue by ifiok** [Supervisor/superlance#114]
Hello!

I would like to extend this application to handle alerts to slack channels. Is that fine?

**Comment by mnaberez** [comment]
Please release it as a standalone plugin and we'll list it on [Supervisor Plugins page](https://github.com/Supervisor/supervisor/blob/363283c71ed11054bdd8756b78e7777f160dcf05/docs/plugins.rst).  There is a Slack plugin listed there already ([superslacker](https://github.com/MTSolutions/superslacker)) so you might consider collaborating on that one instead.

This package, Superlance, was the original set of plugins for Supervisor.  Now there are many more plugins.  All of them are separate, third party packages listed on that page.  New plugins should probably be in their own packages going forward.
