### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by yusupprog** [Supervisor/superlance#121]
<img width="521" alt="Screen Shot 2019-06-24 at 06 13 07" src="https://user-images.githubusercontent.com/11705239/60025406-63449300-96bb-11e9-83af-c07eccbac29d.png">
<img width="435" alt="Screen Shot 2019-06-24 at 06 13 29" src="https://user-images.githubusercontent.com/11705239/60025407-63449300-96bb-11e9-800b-fa43c1ddd01a.png">
<img width="731" alt="Screen Shot 2019-06-24 at 06 13 43" src="https://user-images.githubusercontent.com/11705239/60025408-63449300-96bb-11e9-8472-c81cdbc91890.png">

Hi. Can't configure memmon to restart express-server when memory limit is exceeded on Ubuntu 18

**Comment by cteta** [comment]
would you please paste the error/stdout log ?

**Comment by mnaberez** [comment]
Closing due to no further feedback.  More information (logs) would be needed to troubleshoot this issue.
