### ISSUE TITLE
Installing super lance on alpine based docker images

### ISSUE THREAD

**Issue by mjannapureddy07** [Supervisor/superlance#128]
I  am trying to set up a memmon event listener to monitor the process memory and restart the high memory consuming process inside one of our containers whose base image is alpine. I did install the pip latest version and installed the superlance with pip. I update my supervisord config with the event listener. however when I look at the supervisorctl status, the memmon process get indefinite STARTING loop. I stopped the memmon from supervisorctl and started it manually through command line inside the container. i get the below error:

**Traceback (most recent call last):
  File "/usr/bin/memmon", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/superlance/memmon.py", line 417, in main
    memmon.rpc = childutils.getRPCInterface(os.environ)
  File "/usr/lib/python2.7/site-packages/supervisor/childutils.py", line 17, in getRPCInterface
    return xmlrpclib.ServerProxy('http://127.0.0.1', getRPCTransport(env))
  File "/usr/lib/python2.7/site-packages/supervisor/childutils.py", line 11, in getRPCTransport
    return SupervisorTransport(u, p, env['SUPERVISOR_SERVER_URL'])
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'SUPERVISOR_SERVER_URL**

Can anyone help me understand this error? 

Below is the error from Supervisor logs: 

**Traceback (most recent call last):
  File "/usr/bin/memmon", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/superlance/memmon.py", line 418, in main
    memmon.runforever()
  File "/usr/lib/python2.7/site-packages/superlance/memmon.py", line 152, in runforever
    infos = self.rpc.supervisor.getAllProcessInfo()
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/site-packages/supervisor/xmlrpc.py", line 519, in request
    '' )
xmlrpclib.ProtocolError: <ProtocolError for 127.0.0.1/RPC2: 401 Unauthorized>**

I also see that memmon start up also breaks my supervisorctl web interface on [inet_http_server] when i do **curl -u username:password http://localhost:9001**  I get 500 error. 

Any help is appreciated!

**Comment by mnaberez** [comment]
> KeyError: 'SUPERVISOR_SERVER_URL
>
> Can anyone help me understand this error?

`SUPERVISOR_SERVER_URL` is an environment variable that `supervisord` puts into the environment of its subprocesses.  This error indicates that `memmon` was run outside of `supervisord`.  `memmon` is an [eventlistener](http://supervisord.org/events.html#event-listeners-and-event-notifications) that can only be run under `supervisord`.

> File "/usr/lib/python2.7/site-packages/supervisor/xmlrpc.py", line 519, in request
'' )
> xmlrpclib.ProtocolError: <ProtocolError for 127.0.0.1/RPC2: 401 Unauthorized>

`supervisord` has been configured to use authentication in the `[inet_http_server]` section but `memmon` has not been configured to send authentication.  The documentation has an [example](https://github.com/Supervisor/superlance/blame/49d74d9129a3e0c32a92e199588fd61f1fd3a130/docs/memmon.rst#L206-L221) for how to configure it.

> I also see that memmon start up also breaks my supervisorctl web interface on [inet_http_server] when i do curl -u username:password http://localhost:9001 I get 500 error.

There is not enough information here to tell why `supervisord` returned a 500 response.  The main `supervisord` log should contain an error message that will help troubleshoot it.  If it does not, try `loglevel=debug` in the `[supervisord]` section of the config file.
