### ISSUE TITLE
Fix to #110 not available on pip

### ISSUE THREAD

**Issue by gronostajo** [Supervisor/superlance#129]
It seems that the version which gets installed with `pip install superlance` is affected by #110. The issue was fixed over 2 years ago but it's still wasting hours of developers' productivity. Could you please release the patched version?

**Comment by mnaberez** [comment]
[Superlance 2.0.0](https://pypi.org/project/superlance/2.0.0/)

**Comment by gronostajo** [comment]
Thank you!
