### ISSUE TITLE
Let httpok send more signals [feature request]

### ISSUE THREAD

**Issue by jean** [Supervisor/superlance#47]
I would like `httpok` to send `SIGUSR1` before killing a Zope instance, to obtain a thread dump, so that I can figure out what was keeping the instance busy. 

What would be a good way to specify this in configuration? 
Would something like the following make sense?

```diff
diff --git a/superlance/httpok.py b/superlance/httpok.py
index 23682fc..3e7c6b1 100644
--- a/superlance/httpok.py
+++ b/superlance/httpok.py
@@ -280,6 +280,8 @@ class HTTPOk:
                         namespec, m.read()))
             write('%s is in RUNNING state, restarting' % namespec)
             try:
+                for signal in self.signals:
+                    self.rpc.supervisor.signalProcess(namespec, signal)
                 self.rpc.supervisor.stopProcess(namespec)
             except xmlrpclib.Fault as e:
                 write('Failed to stop process %s: %s' % (
```

Raised at https://lists.supervisord.org/pipermail/supervisor-users/2014-September/001520.html too.

(`signalProcess` is not yet in a supervisor release.)

**Comment by mnaberez** [comment]
Support for arbitrary sending signals was released in Supervisor 3.2.0.  I'm not sure what the best way to make this particular feature would be, perhaps it could be something like "`--presignal <signame>` sends a signal before issues stopping" but that's just one idea.  Feel free to submit a patch.
