### ISSUE TITLE
email address from file [Feature Request]

### ISSUE THREAD

**Issue by steeevieee** [Supervisor/superlance#59]
We have the crashmail email go to different addresses based on an on-call rota, and at the moment we have to bounce it weekly to pick up the change. It would be nice to have it read the email address from a file just before sending instead. I'm not good with Python, but something like...

def mail(self, email, subject, msg):
if os.path.isfile(self.email) and os.access(self.email, os.R_OK):
  with open(self.email,'r') as f:
    body = 'To: %s\n' % f.read()
else:
  body = 'To: %s\n' % self.email

**Comment by mnaberez** [comment]
There are some ways to achieve this without modifying this package (e.g. postfix virtual alias table).  I'm going to close this for now but if you really think it's needed, we'd review a PR for it.
