### ISSUE TITLE
Directory monitor for conf files

### ISSUE THREAD

**Issue by krafts** [Supervisor/superlance#63]
Monitors a directory for file changes and sends an event. Did not see an suitable event type for this.

This will help in restarting processes after changes in the conf.d are detected for applications. More specifically this helps when processes are running within containers and the conf.d is mounted on shared volumes. So when placing files, access to processes in other containers not available due to process namespaces being insulated.

**Comment by mnaberez** [comment]
This sounds like a nice idea for a plugin but it doesn't need to be part of the superlance package.  There's now a large number of [third party plugins](http://supervisord.org/plugins.html).  Installation of third party packages is the same process as installation of the superlance package, so for most cases we probably don't need to add new plugins into this package.  If you write a plugin for this, we would be happy to link to it on [the plugins page](https://github.com/Supervisor/supervisor/blob/3.3.1/docs/plugins.rst).
