### ISSUE TITLE
Sphinx warnings when building from a PyPI tarball

### ISSUE THREAD

**Issue by sbraz** [Supervisor/superlance#92]
Hi,
When I build the doc from PyPI's 0.13 tarball, I see this:
```
superlance-0.13/docs/index.rst:44: WARNING: toctree contains reference to nonexisting document u'development'
```
and
```
copying static files... WARNING: html_static_path entry u'/var/tmp/portage/dev-python/superlance-0.13/work/superlance-0.13/docs/_static' does not exist
```
Do you think you could include the `development.rst` file and the `_static` directory (or just remove the relevant line from `conf.py`)?

**Comment by sbraz** [comment]
@mnaberez Thanks for the commit :)
I have an unrelated question about the way you handle the tags: it seems that 0.13 contains all the commits from 0.12 except the Python 3 ones and those commits look like duplicates of the master branch ones, is that normal?
![commits](https://cloud.githubusercontent.com/assets/4833332/18290134/9d1d12a4-7482-11e6-84cd-871b5d2bee9c.png)

**Comment by mnaberez** [comment]
Yeah, the Python 3 work isn't released yet.  Supervisor itself doesn't work on Python 3 ([issues](https://github.com/Supervisor/supervisor/issues?q=is%3Aopen+is%3Aissue+label%3A%22python+3%22)).  The Python 3 stuff used to be in a branch but a bunch of people wanted it in master which created this awkward cherry-pick workflow for the stable work.  The Python 3 situation is a large and difficult problem.  I'm just trying to get bug fixes out for the stable version in the meantime.

**Comment by sbraz** [comment]
Seems reasonable, thanks :)

**Comment by mnaberez** [comment]
https://pypi.python.org/pypi/superlance/0.14
