### ISSUE TITLE
how to limit email from crashmail  

### ISSUE THREAD

**Issue by gchokeen** [Supervisor/superlance#99]
We are running many supervisor tasks. when server facing some problem. crashmail sendout email to configured email id. That's good, but sometime if not able to immediately  resolve the server issue, crashmail sends out thousands of email. So Is there any option to limit the email for specific period?

**Comment by mnaberez** [comment]
> So Is there any option to limit the email for specific period?

`crashmail` doesn't have an option to stop sending alerts for programs it is watching.  Instead, you can do one of the following:

- Change the list of programs `crashmail` is watching so the program you want to stop alerting on is no longer included in the list.
- Stop `crashmail` from running entirely with `supervisorctl stop crashmail`.
